// Regenerate with `bun run bindings`; CI fails when this file is out of date.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns facts about the running app. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Returns the current settings. */
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**
	 *  Changes the settings present in `patch` (e.g. `{ uiLanguage: "en" }`) and saves them at once.
	 *  Returns the new settings; every window also receives them as a `SettingsChanged` event.
	 */
	updateSettings: (patch: SettingsPatch) => typedError<Settings, string>(__TAURI_INVOKE("update_settings", { patch })),
	/**  Puts the setting `key` (e.g. `"uiLanguage"`) back to its default. */
	resetSetting: (key: string) => typedError<Settings, string>(__TAURI_INVOKE("reset_setting", { key })),
	/**
	 *  Opens the folder with Echo's log files in File Explorer (the "Open log folder" link in the
	 *  App section, `settings-and-first-run.md` "UI").
	 */
	openLogFolder: () => typedError<null, string>(__TAURI_INVOKE("open_log_folder")),
	/**
	 *  Opens the Windows microphone privacy settings ("Open Windows privacy settings" in the
	 *  onboarding's Microphone access step).
	 */
	openMicrophonePrivacySettings: () => typedError<null, string>(__TAURI_INVOKE("open_microphone_privacy_settings")),
	/**
	 *  A fresh list of the input devices and the current Windows default. The Microphone picker
	 *  asks for it every time it opens (`microphone.md` rule 8).
	 */
	listMicrophones: () => typedError<DeviceList, string>(__TAURI_INVOKE("list_microphones")),
	/**
	 *  Whether Windows privacy settings let desktop apps use the Microphone (`microphone.md` rule 7;
	 *  the onboarding's Microphone access step).
	 */
	microphoneAccess: () => __TAURI_INVOKE<MicrophoneAccess>("microphone_access"),
	/**  Returns the Models and their state. */
	getModels: () => __TAURI_INVOKE<ModelsState>("get_models"),
	/**  Starts downloading a Model, or queues it behind the running download. */
	downloadModel: (model: ModelId) => __TAURI_INVOKE<void>("download_model", { model }),
	/**  Cancels a running or queued download; the partial file is kept for "Resume". */
	cancelModelDownload: (model: ModelId) => __TAURI_INVOKE<void>("cancel_model_download", { model }),
	/**
	 *  Makes a downloaded Model active. Returns once loading has started; the result arrives as a
	 *  `ModelsChanged` event (active, or a `loadFailure`).
	 */
	activateModel: (model: ModelId) => typedError<null, string>(__TAURI_INVOKE("activate_model", { model })),
	/**  Deletes a downloaded Model or a paused download. */
	deleteModel: (model: ModelId) => typedError<null, string>(__TAURI_INVOKE("delete_model", { model })),
	/**
	 *  Validates and activates a new Record Shortcut given in canonical text form (`"Ctrl+Space"`),
	 *  then saves it. On failure the previous one stays active and saved. Ends a capture in progress.
	 *  Returns the new settings (every window also receives them as a `SettingsChanged` event).
	 */
	setRecordShortcut: (combination: string) => typedError<Settings, ShortcutChangeError>(__TAURI_INVOKE("set_record_shortcut", { combination })),
	/**
	 *  Starts shortcut capture: the Record Shortcut is suspended and keys arrive as
	 *  [`CapturedKeyEvent`]s instead of reaching applications.
	 */
	beginShortcutCapture: () => typedError<null, string>(__TAURI_INVOKE("begin_shortcut_capture")),
	/**  Ends shortcut capture without changes. */
	endShortcutCapture: () => __TAURI_INVOKE<void>("end_shortcut_capture"),
	/**
	 *  A key pressed or released in Echo's own window, by capture name. Windows does not run Echo's
	 *  keyboard hook while Echo's window has focus, so the window forwards its keys here.
	 */
	ownWindowKey: (key: string, pressed: boolean) => __TAURI_INVOKE<void>("own_window_key", { key, pressed }),
};

/** Events */
export const events = {
	capturedKeyEvent: makeEvent<CapturedKeyEvent>("captured-key-event"),
	modelProblemOccurred: makeEvent<ModelProblemOccurred>("model-problem-occurred"),
	modelsChanged: makeEvent<ModelsChanged>("models-changed"),
	recordIntentEvent: makeEvent<RecordIntentEvent>("record-intent-event"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
};

/* Types */
export type ActiveModelState = 
/**  No Model is active. */
"none" | "loading" | "ready" | 
/**  Unloaded after inactivity; loads on the next Dictation (rule 24b). */
"unloaded" | 
/**  The active Model could not be loaded (e.g. at start); the next Dictation tries again. */
"error";

/**  Facts about the running app that the interface needs at start-up. */
export type AppInfo = {
	/**  Echo's version, e.g. `0.1.0`. */
	version: string,
	/**  The Windows display language as a BCP 47 tag, if Windows reports one. */
	systemLocale: string | null,
};

/**
 *  A key pressed or released during shortcut capture, by its capture name (`"LeftCtrl"`,
 *  `"RightAlt"`, `"Space"`, `"F9"`).
 */
export type CapturedKeyEvent = {
	key: string,
	pressed: boolean,
};

/**  The input devices present right now. */
export type DeviceList = {
	/**  Names of every input device, in the order Windows lists them. */
	devices: string[],
	/**  Name of the Windows default recording device, if there is one. */
	default: string | null,
};

/**  Why a download failed, for a plain-language message in the UI. */
export type DownloadFailure = {
	kind: FailureKind,
	/**  Technical detail (in English) shown under the message. */
	detail: string,
	/**  For [`FailureKind::DiskSpace`]: the free space needed, in bytes. */
	neededBytes: number | null,
};

/**
 *  Where a Model's download stands. `Idle` covers both "not downloaded" and "downloaded";
 *  [`ModelEntry::downloaded`] tells them apart.
 */
export type DownloadState = { state: "idle" } | 
/**  Waiting for another download to finish (rule 7). */
{ state: "queued" } | { state: "downloading"; downloaded: number; total: number; bytesPerSecond: number } | 
/**  "Verifying…" (rule 13). */
{ state: "verifying" } | 
/**  "Paused — X% downloaded", with Resume and Delete (rule 14). */
{ state: "paused"; downloaded: number; total: number } | 
/**
 *  A failed download with its reason and "Retry" (rule 16). `downloaded` is what the partial
 *  file kept for the retry.
 */
{ state: "failed"; failure: DownloadFailure; downloaded: number; total: number };

export type FailureKind = "network" | "stalled" | "badRange" | "sizeMismatch" | 
/**  "Download was corrupted — please try again" (rule 12). */
"corrupted" | "storage" | "diskSpace";

export type LoadFailure = {
	model: ModelId,
	reason: string,
};

/**  Whether Windows privacy settings let desktop apps use the Microphone (rule 7). */
export type MicrophoneAccess = "allowed" | "denied";

/**
 *  The Microphone setting (`microphone.md` rules 1–2): follow the Windows default recording
 *  device, or one specific device identified by its name as Windows reports it.
 * 
 *  Stored as `{"kind": "default"}` or `{"kind": "device", "name": "Microphone (USB Audio)"}`.
 */
export type MicrophoneChoice = 
/**  Whatever Windows considers the default recording device when a Recording starts. */
{ kind: "default" } | 
/**  One specific device, by name. */
{ kind: "device"; name: string };

/**
 *  One Model as shown on its card. Byte counts are `u32`: every 0.1.0 Model is under 4 GiB, and
 *  TypeScript numbers carry them exactly.
 */
export type ModelEntry = {
	id: ModelId,
	name: string,
	sizeBytes: number,
	languages: number,
	recommended: boolean,
	/**  The verified file is present (rule 5). */
	downloaded: boolean,
	download: DownloadState,
};

/**
 *  One of the Models Echo offers. The order of [`ModelId::ALL`] is the list order used in the UI
 *  and for every "first downloaded Model in list order" fallback (rules 23 and 26).
 */
export type ModelId = "whisperLargeV3Turbo" | "parakeetTdt06bV3" | "whisperSmall";

/**
 *  A download or load failure, for the error indication of `dictation-pipeline.md` rules
 *  39a–39d (Overlay message, red tray icon, window notice).
 */
export type ModelProblem = {
	kind: ModelProblemKind,
	model: ModelId,
	/**  The Model's name, for the tray tooltip. */
	modelName: string,
	/**  Technical detail in English. */
	detail: string,
};

export type ModelProblemKind = "download" | "load";

/**
 *  Sent when a Model download or load fails (the error indication, `dictation-pipeline.md`
 *  rules 39a–39d).
 */
export type ModelProblemOccurred = ModelProblem;

/**
 *  Sent to every window after any change to the Models: downloads and their progress, the
 *  active Model and its state.
 */
export type ModelsChanged = ModelsState;

/**  Everything the Models page, the Model indicator and the onboarding show. */
export type ModelsState = {
	/**  The three Models in list order. */
	models: ModelEntry[],
	/**  The active Model, if any (rule 17). */
	active: ModelId | null,
	/**  Whether the active Model is in memory. */
	activeState: ActiveModelState,
	/**  The Model being loaded to become active ("Loading <Model>…", rule 18). */
	activating: ModelId | null,
	/**  The latest failed load ("Couldn't load <Model>", rule 19), until the next successful one. */
	loadFailure: LoadFailure | null,
	/**
	 *  A Dictation is Recording or Transcribing: switching and deleting are disabled
	 *  (rules 20, 27).
	 */
	dictationInProgress: boolean,
};

/**  What the Record Shortcut asks the dictation pipeline to do. */
export type RecordIntent = 
/**  Start a Recording (or, while busy, remember the request — `dictation-pipeline.md` 27–29). */
"start" | 
/**  Stop the Recording (or, while busy, forget the remembered request). */
"stop";

/**
 *  TEMPORARY (remove with #13): every Record Shortcut intent, so the hook can be checked by hand
 *  on the Dictation page until the dictation pipeline consumes the intents.
 */
export type RecordIntentEvent = {
	intent: RecordIntent,
};

/**
 *  The Record Shortcut setting: an allowed combination (rules 19–20) in canonical text form,
 *  e.g. `"Ctrl+Space"`. Deserializing accepts exactly the allowed combinations, so an invalid
 *  stored value falls back to the default (`docs/settings.md`). The check against the current
 *  Cancel Shortcut uses its default until the Cancel Shortcut becomes a setting (#15).
 */
export type RecordShortcutCombination = string;

/**
 *  Every persisted setting, one top-level field per setting. Each field is salvaged on
 *  its own: an invalid value resets only that field to its default (rule 13).
 */
export type Settings = {
	/**  The language of Echo's own interface (owned by `settings-and-first-run.md`). */
	uiLanguage: UiLanguage,
	/**
	 *  The user has moved past the Welcome step of the onboarding (`settings-and-first-run.md`
	 *  rules 1–4). The Microphone access and Choose a Model steps are not stored: they are
	 *  complete when Windows allows microphone access and when a Model is active.
	 */
	onboardingWelcomeDone: boolean,
	/**  The user pressed "Finish" in the onboarding; it is never shown again (rule 5). */
	onboardingCompleted: boolean,
	/**  The input device Recordings listen to (`microphone.md`). */
	microphone: MicrophoneChoice,
	/**
	 *  The Model Dictations use, or none (`models.md` rules 17–23). Owned by the Model manager:
	 *  change it with the `activate_model` command, which loads the Model first and keeps the
	 *  previous one if loading fails — never through `update_settings`.
	 */
	activeModel: ModelId | null,
	/**
	 *  Unload the active Model from memory after this much time without a Dictation
	 *  (`models.md` rule 24a).
	 */
	unloadModelAfter: UnloadModelAfter,
	/**  The key combination that starts and stops a Recording (`record-shortcut.md`). */
	recordShortcut: RecordShortcutCombination,
	/**  Push-to-Talk Mode or Toggle Mode (`record-shortcut.md`). */
	shortcutMode: ShortcutMode,
};

/**  Sent to every window after any change to the settings, with the complete new settings. */
export type SettingsChanged = Settings;

/**  A change to some settings: only the fields that are present change. */
export type SettingsPatch = {
	/**  The language of Echo's own interface (owned by `settings-and-first-run.md`). */
	uiLanguage?: UiLanguage | null,
	/**
	 *  The user has moved past the Welcome step of the onboarding (`settings-and-first-run.md`
	 *  rules 1–4). The Microphone access and Choose a Model steps are not stored: they are
	 *  complete when Windows allows microphone access and when a Model is active.
	 */
	onboardingWelcomeDone?: boolean | null,
	/**  The user pressed "Finish" in the onboarding; it is never shown again (rule 5). */
	onboardingCompleted?: boolean | null,
	/**  The input device Recordings listen to (`microphone.md`). */
	microphone?: MicrophoneChoice | null,
	/**
	 *  The Model Dictations use, or none (`models.md` rules 17–23). Owned by the Model manager:
	 *  change it with the `activate_model` command, which loads the Model first and keeps the
	 *  previous one if loading fails — never through `update_settings`.
	 */
	activeModel?: ModelId | null,
	/**
	 *  Unload the active Model from memory after this much time without a Dictation
	 *  (`models.md` rule 24a).
	 */
	unloadModelAfter?: UnloadModelAfter | null,
	/**  The key combination that starts and stops a Recording (`record-shortcut.md`). */
	recordShortcut?: RecordShortcutCombination | null,
	/**  Push-to-Talk Mode or Toggle Mode (`record-shortcut.md`). */
	shortcutMode?: ShortcutMode | null,
};

/**  Why a new Record Shortcut was not taken; the previous one stays active (rule 23). */
export type ShortcutChangeError = 
/**  The combination is not allowed (rule 20). */
{ kind: "notAllowed"; problem: ShortcutProblem } | 
/**  The combination is allowed but could not be activated (or saved). */
{ kind: "activationFailed"; reason: string };

/**  How the Record Shortcut starts and stops a Recording. */
export type ShortcutMode = 
/**  Hold to record (the default, rule 5). */
"pushToTalk" | 
/**  Press to start, press again to stop. */
"toggle";

/**
 *  Why a proposed combination cannot be the Record Shortcut (rule 20). The interface shows a
 *  message for each.
 */
export type ShortcutProblem = 
/**  No keys at all. */
"empty" | 
/**
 *  A character key, Space or another typing key without a modifier: it would stop working
 *  for typing.
 */
"needsModifier" | 
/**  A single modifier other than right Alt or right Ctrl. */
"singleModifier" | 
/**  Escape alone is reserved as the default Cancel Shortcut. */
"escapeReserved" | 
/**  Windows handles this combination itself and never delivers it to applications. */
"reservedByWindows" | 
/**  The same combination as the Cancel Shortcut. */
"sameAsCancel" | 
/**  Not a combination Echo understands (unknown key name, two main keys, …). */
"invalid";

/**  The language of Echo's own interface. Independent of the Dictation Language (rule 9). */
export type UiLanguage = "pl" | "en";

/**  The "Unload Model after inactivity" choices (`models.md` "Settings"). */
export type UnloadModelAfter = "never" | "minutes2" | "minutes5" | "minutes10" | "minutes15" | "minutes60";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

