// Regenerate with `bun run bindings`; CI fails when this file is out of date.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns facts about the running app. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  Facts about the running app that the interface needs at start-up. */
export type AppInfo = {
	/**  Echo's version, e.g. `0.1.0`. */
	version: string,
	/**  The Windows display language as a BCP 47 tag, if Windows reports one. */
	systemLocale: string | null,
	/**  The UI Language to use until the user picks one. */
	defaultUiLanguage: UiLanguage,
};

/**  The language of Echo's own interface. */
export type UiLanguage = "pl" | "en";

