// Regenerate with `bun run bindings`; CI fails when this file is out of date.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns facts about the running app. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Returns the current settings. */
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**
	 *  Changes the settings present in `patch` (e.g. `{ uiLanguage: "en" }`) and saves them at once.
	 *  Returns the new settings; every window also receives them as a `SettingsChanged` event.
	 */
	updateSettings: (patch: SettingsPatch) => typedError<Settings, string>(__TAURI_INVOKE("update_settings", { patch })),
	/**  Puts the setting `key` (e.g. `"uiLanguage"`) back to its default. */
	resetSetting: (key: string) => typedError<Settings, string>(__TAURI_INVOKE("reset_setting", { key })),
	/**  Every History entry, newest first. */
	listHistory: () => typedError<HistoryEntry[], string>(__TAURI_INVOKE("list_history")),
	/**
	 *  Permanently deletes one entry and returns it (or `null` if it was already gone), so the
	 *  window can offer Undo for 5 s (rule 12).
	 */
	deleteHistoryEntry: (id: number) => typedError<{
	/**  Unique and never reused, even after the entry is deleted. */
	id: number,
	/**
	 *  When the entry was created, in milliseconds since the Unix epoch (UTC). Shown in local
	 *  time.
	 */
	createdAt: number,
	/**  The Transcript exactly as inserted. */
	text: string,
	/**  The id of the Model that produced it (`models.md`). */
	model: string,
	/**  The effective Dictation Language. */
	language: EntryLanguage,
} | null, string>(__TAURI_INVOKE("delete_history_entry", { id })),
	/**  Puts back an entry returned by `delete_history_entry`, with its original id and time (Undo). */
	restoreHistoryEntry: (entry: HistoryEntry) => typedError<null, string>(__TAURI_INVOKE("restore_history_entry", { entry })),
	/**  Deletes every entry; the window asks for confirmation first (rule 14). */
	clearHistory: () => typedError<null, string>(__TAURI_INVOKE("clear_history")),
	/**
	 *  Hides Echo's window and inserts the entry's text into the application that had focus before
	 *  (rule 13). If Insertion fails, the window comes back so the user sees the error.
	 */
	reinsertHistoryEntry: (id: number) => typedError<null, string>(__TAURI_INVOKE("reinsert_history_entry", { id })),
	/**
	 *  Opens the folder with Echo's log files in File Explorer (the "Open log folder" link in the
	 *  App section, `settings-and-first-run.md` "UI").
	 */
	openLogFolder: () => typedError<null, string>(__TAURI_INVOKE("open_log_folder")),
	/**
	 *  Opens the Windows microphone privacy settings ("Open Windows privacy settings" in the
	 *  onboarding's Microphone access step).
	 */
	openMicrophonePrivacySettings: () => typedError<null, string>(__TAURI_INVOKE("open_microphone_privacy_settings")),
};

/** Events */
export const events = {
	historyChanged: makeEvent<HistoryChanged>("history-changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
};

/* Types */
/**  Facts about the running app that the interface needs at start-up. */
export type AppInfo = {
	/**  Echo's version, e.g. `0.1.0`. */
	version: string,
	/**  The Windows display language as a BCP 47 tag, if Windows reports one. */
	systemLocale: string | null,
};

/**  The effective Dictation Language of a stored Transcript. */
export type EntryLanguage = 
/**  Automatic detection, with the language the Engine detected if it reported one. */
{ kind: "automatic"; detected: string | null } | 
/**  A chosen language: an ISO 639-1 code such as `"pl"`. */
{ kind: "specific"; code: string };

/**  Sent to every window after any change to History, with every entry, newest first (rule 16). */
export type HistoryChanged = HistoryEntry[];

/**  One stored Transcript (rule 3). */
export type HistoryEntry = {
	/**  Unique and never reused, even after the entry is deleted. */
	id: number,
	/**
	 *  When the entry was created, in milliseconds since the Unix epoch (UTC). Shown in local
	 *  time.
	 */
	createdAt: number,
	/**  The Transcript exactly as inserted. */
	text: string,
	/**  The id of the Model that produced it (`models.md`). */
	model: string,
	/**  The effective Dictation Language. */
	language: EntryLanguage,
};

/**
 *  How many entries History keeps: an integer 0–100, default 5; 0 keeps nothing (`history.md`
 *  rules 6–9). Deserialising rejects anything outside the range, so invalid stored values are
 *  salvaged to the default and invalid patches are refused.
 */
export type HistoryLimit = number;

/**
 *  Every persisted setting, one top-level field per setting. Each field is salvaged on
 *  its own: an invalid value resets only that field to its default (rule 13).
 */
export type Settings = {
	/**  The language of Echo's own interface (owned by `settings-and-first-run.md`). */
	uiLanguage: UiLanguage,
	/**
	 *  The user has moved past the Welcome step of the onboarding (`settings-and-first-run.md`
	 *  rules 1–4). The Microphone access and Choose a Model steps are not stored: they are
	 *  complete when Windows allows microphone access and when a Model is active.
	 */
	onboardingWelcomeDone: boolean,
	/**  The user pressed "Finish" in the onboarding; it is never shown again (rule 5). */
	onboardingCompleted: boolean,
	/**  How many Transcripts History keeps (`history.md` rules 6–9). */
	historyLimit: HistoryLimit,
};

/**  Sent to every window after any change to the settings, with the complete new settings. */
export type SettingsChanged = Settings;

/**  A change to some settings: only the fields that are present change. */
export type SettingsPatch = {
	/**  The language of Echo's own interface (owned by `settings-and-first-run.md`). */
	uiLanguage?: UiLanguage | null,
	/**
	 *  The user has moved past the Welcome step of the onboarding (`settings-and-first-run.md`
	 *  rules 1–4). The Microphone access and Choose a Model steps are not stored: they are
	 *  complete when Windows allows microphone access and when a Model is active.
	 */
	onboardingWelcomeDone?: boolean | null,
	/**  The user pressed "Finish" in the onboarding; it is never shown again (rule 5). */
	onboardingCompleted?: boolean | null,
	/**  How many Transcripts History keeps (`history.md` rules 6–9). */
	historyLimit?: HistoryLimit | null,
};

/**  The language of Echo's own interface. Independent of the Dictation Language (rule 9). */
export type UiLanguage = "pl" | "en";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

