//! The **WAV Audio Source**: plays a WAV file as if it were a Microphone, for tests and
//! fake-microphone mode (`dictation-pipeline.md` rules 40–46).

use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;
use std::time::{Duration, Instant};

use super::{
    AudioEvent, AudioFormat, AudioFrames, AudioSink, AudioSource, AudioSourceError, AudioStream,
};

/// How fast the WAV Audio Source delivers the file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Pace {
    /// One second of audio per second, like a Microphone (rule 43).
    #[default]
    RealTime,
    /// The whole file immediately, for unit tests that do not involve timing (rule 45).
    AsFastAsPossible,
}

/// Test options of the WAV Audio Source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct WavOptions {
    pub pace: Pace,
    /// Report [`AudioEvent::Ended`](super::AudioEvent::Ended) at the end of the file instead of
    /// delivering silence until the Recording is stopped (rule 44).
    pub stop_at_end: bool,
}

/// An [`AudioSource`] that plays a PCM WAV file (16-bit integer or 32-bit float, any sample rate
/// and channel count) from its beginning at every Recording.
///
/// The file is decoded once, up front, so a broken file is reported when fake-microphone mode is
/// set up rather than at the first Recording. Audio is delivered in 10 ms pieces from a
/// dedicated thread. After the end of the file it delivers silence in real time until stopped
/// (even with [`Pace::AsFastAsPossible`], so an unattended stream cannot flood memory), unless
/// [`WavOptions::stop_at_end`] is set.
pub struct WavAudioSource {
    format: AudioFormat,
    samples: Arc<[f32]>,
    options: WavOptions,
}

impl WavAudioSource {
    /// Reads and decodes the WAV file at `path`.
    pub fn open(path: impl AsRef<Path>, options: WavOptions) -> Result<Self, AudioSourceError> {
        let path = path.as_ref();
        let file = File::open(path).map_err(|e| {
            AudioSourceError::Failed(format!("cannot open WAV file {}: {e}", path.display()))
        })?;
        Self::from_reader(BufReader::new(file), options).map_err(|e| match e {
            AudioSourceError::Failed(detail) => {
                AudioSourceError::Failed(format!("{}: {detail}", path.display()))
            }
            other => other,
        })
    }

    /// Decodes a WAV file from any reader, e.g. an in-memory buffer generated by a test.
    pub fn from_reader(reader: impl Read, options: WavOptions) -> Result<Self, AudioSourceError> {
        let invalid = |e: hound::Error| AudioSourceError::Failed(format!("invalid WAV file: {e}"));
        let reader = hound::WavReader::new(reader).map_err(invalid)?;
        let spec = reader.spec();
        let samples: Vec<f32> = match (spec.sample_format, spec.bits_per_sample) {
            (hound::SampleFormat::Float, 32) => reader
                .into_samples::<f32>()
                .collect::<Result<_, _>>()
                .map_err(invalid)?,
            (hound::SampleFormat::Int, bits @ 1..=32) => {
                let scale = 1.0 / (1u64 << (bits - 1)) as f32;
                reader
                    .into_samples::<i32>()
                    .map(|s| s.map(|s| s as f32 * scale))
                    .collect::<Result<_, _>>()
                    .map_err(invalid)?
            }
            (format, bits) => {
                return Err(AudioSourceError::Failed(format!(
                    "unsupported WAV sample format: {bits}-bit {format:?}"
                )));
            }
        };
        if spec.channels == 0 || spec.sample_rate == 0 {
            return Err(AudioSourceError::Failed(
                "WAV file has no channels or no sample rate".into(),
            ));
        }
        Ok(Self {
            format: AudioFormat {
                sample_rate: spec.sample_rate,
                channels: spec.channels,
            },
            samples: samples.into(),
            options,
        })
    }

    /// Format of the decoded file, which is also the format of every delivered piece.
    pub fn format(&self) -> AudioFormat {
        self.format
    }
}

impl AudioSource for WavAudioSource {
    fn start(&mut self, sink: AudioSink) -> Result<AudioStream, AudioSourceError> {
        let stop = Arc::new(AtomicBool::new(false));
        let player = Player {
            format: self.format,
            samples: Arc::clone(&self.samples),
            options: self.options,
            stop: Arc::clone(&stop),
            sink,
        };
        let worker = thread::Builder::new()
            .name("wav-audio-source".into())
            .spawn(move || player.run())
            .map_err(|e| AudioSourceError::Failed(format!("cannot start WAV playback: {e}")))?;

        Ok(AudioStream::new(move || {
            stop.store(true, Ordering::SeqCst);
            worker.thread().unpark();
            if worker.thread().id() != thread::current().id() {
                // The sink is dropped when the worker returns, honouring the stop contract.
                let _ = worker.join();
            }
        }))
    }
}

/// Length of one delivered piece.
const PIECE: Duration = Duration::from_millis(10);

/// The playback thread of one Recording.
struct Player {
    format: AudioFormat,
    samples: Arc<[f32]>,
    options: WavOptions,
    stop: Arc<AtomicBool>,
    sink: AudioSink,
}

impl Player {
    fn run(mut self) {
        let channels = self.format.channels as usize;
        let rate = self.format.sample_rate as u64;
        let piece_frames = ((rate * PIECE.as_millis() as u64) / 1000).max(1) as usize;
        let total_frames = self.samples.len() / channels;

        let mut position = 0; // frames of the file already delivered
        // Real-time pacing: frames delivered since `clock_start`.
        let mut clock_start = Instant::now();
        let mut paced_frames: u64 = 0;
        let mut paced = self.options.pace == Pace::RealTime;

        while !self.stop.load(Ordering::SeqCst) {
            let samples = if position < total_frames {
                let end = (position + piece_frames).min(total_frames);
                let piece = self.samples[position * channels..end * channels].to_vec();
                position = end;
                piece
            } else if self.options.stop_at_end {
                (self.sink)(AudioEvent::Ended);
                return;
            } else {
                if !paced {
                    // Trailing silence is always real-time, from the moment the file ended.
                    paced = true;
                    clock_start = Instant::now();
                    paced_frames = 0;
                }
                vec![0.0; piece_frames * channels]
            };
            let frames = (samples.len() / channels) as u64;
            (self.sink)(AudioEvent::Frames(AudioFrames {
                format: self.format,
                samples,
            }));

            if paced {
                paced_frames += frames;
                let due = clock_start + Duration::from_micros(paced_frames * 1_000_000 / rate);
                self.sleep_until(due);
            }
        }
    }

    /// Sleeps until `deadline`, waking early when the stream is stopped.
    fn sleep_until(&self, deadline: Instant) {
        loop {
            if self.stop.load(Ordering::SeqCst) {
                return;
            }
            let now = Instant::now();
            if now >= deadline {
                return;
            }
            thread::park_timeout(deadline - now);
        }
    }
}
