//! The tray glyphs generated by `bun run tray-icons` (`scripts/tray-icons.ts`) into
//! `src-tauri/icons/tray/`, compiled in.

use super::{TaskbarTheme, TrayIconState};

/// The pixel sizes drawn on their own grid: the notification-area icon size at 100, 125, 150
/// and 200 % display scale.
pub const SIZES: [u32; 4] = [16, 20, 24, 32];

/// The icon size for a display scale factor: the smallest drawn size that is not smaller than
/// what Windows shows, so the glyph is never scaled up.
pub fn size_for_scale(scale: f64) -> u32 {
    let wanted = (16.0 * scale).round();
    SIZES
        .into_iter()
        .find(|&size| f64::from(size) >= wanted)
        .unwrap_or(SIZES[SIZES.len() - 1])
}

macro_rules! glyphs {
    ($($state:literal),*) => {
        /// `(state, variant, size, png)` for every generated glyph.
        const GLYPHS: &[(&str, &str, u32, &[u8])] = &[
            $(
                glyphs!(@one $state, "dark", 16), glyphs!(@one $state, "dark", 20),
                glyphs!(@one $state, "dark", 24), glyphs!(@one $state, "dark", 32),
                glyphs!(@one $state, "light", 16), glyphs!(@one $state, "light", 20),
                glyphs!(@one $state, "light", 24), glyphs!(@one $state, "light", 32),
            )*
        ];
    };
    (@one $state:literal, $variant:literal, $size:literal) => {
        (
            $state,
            $variant,
            $size,
            include_bytes!(concat!(
                "../../icons/tray/", $state, "-", $variant, "-", stringify!($size), ".png"
            )),
        )
    };
}

glyphs!("idle", "recording", "transcribing", "error");

/// The PNG for a state on a taskbar theme at one of [`SIZES`] (other sizes get the largest).
pub fn png(state: TrayIconState, theme: TaskbarTheme, size: u32) -> &'static [u8] {
    let state = match state {
        TrayIconState::Idle => "idle",
        TrayIconState::Recording => "recording",
        TrayIconState::Transcribing => "transcribing",
        TrayIconState::Error => "error",
    };
    // A light taskbar gets the dark glyph (rule 3).
    let variant = match theme {
        TaskbarTheme::Light => "dark",
        TaskbarTheme::Dark => "light",
    };
    let size = if SIZES.contains(&size) { size } else { 32 };
    GLYPHS
        .iter()
        .find(|(s, v, z, _)| *s == state && *v == variant && *z == size)
        .map(|(_, _, _, png)| *png)
        .expect("every glyph is generated")
}
